<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<section id="values_section">
    <div class="container">
        <div class="row values_main">
            <div class="col-12 values_content">
                <div class="main_vision_value">
                    <h2 id="res_term_respo" class="head_clr"><span class="head_name_color">PRIVACY </span>POLICY</h2>
                </div>
                <div class="values_p_">
                    <p><span><i class="far fa-hand-point-right"></i>  We respect your privacy and are committed to maintaining it. When you shop on our shopping store, we will ask you to input your information and will collect Personal Information from you such as your name, e-mail address, billing address, shipping address, telephone/ mobile number, product selections, credit card or other payment information and password.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  We recognize your right to confidentiality and are committed to protecting your privacy. We do not furnish any identifiable information at the individual level regarding its customers to any third party. The information you give to us is held with the utmost care and security. This information is collected primarily to ensure that we are able to fulfill your requirements and to deliver you a truly personalized shopping experience. When navigating our web site, personal information about you is not collected automatically or without your knowledge.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  We are also bound to cooperate fully should a situation arise where we are required by law or legal process to provide information about a customer. We may share non-personal, non-individual statistical or demographic information in aggregate form with our marketing partners, advertisers or other third-parties for research and advertising purposes. In other words, we will not tell our marketing partners that you purchased a specific product, but we may tell them how many customers purchased that product.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  If you consent, to notify you of products or special offers that may be of interest to you. You agree that you do not object to us contacting you for any of the above purposes whether by telephone, e-mail or in writing and you confirm that you do not and will not consider any of the above as being a breach of any of your rights under the Telecommunications (Data Protection and Privacy) Regulations 1999.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  We will not release your Personal Information to any company outside for mailing or marketing purposes.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  We use 'Cookies' to keep track of your current shopping session to personalize your experience and so that you may retrieve your shopping cart at any time. 'Cookies' are tiny text files which our Website places on your computer's hard drive to store information about your shopping session and to identify your computer. `Cookies` cannot harm your computer and do not contain any personal or private information. We do not hold any of your credit card information. This information is securely collected by our authorized payment processors.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  In short, we always strive to respect the privacy of our customers completely. We use the information we collect on the Store to enhance your overall shopping experience. We do not sell, trade, or rent your personal information to others.We do not hold any of your credit card information. This information is securely collected by our authorized payment gateways. With the industry's most-advanced encryption, fraud prevention and protection policies, our payment gateways are dedicated to keeping your account safe and secure. Once your information reaches our payment gateways it resides on a server that is heavily guarded both physically and electronically.</span></p>
                    <div class="main_vision_value_">
                        <h2 class="head_clr"><span class="head_name_color">Your Privacy</span> - Our Commitment</h2>
                    </div>
                    <p><span><i class="far fa-hand-point-right"></i>  eShoplik.com, through its website, is extremely proud of it’s commitment to protect your privacy. We value your trust in us. We will work hard to earn your confidence so that you can enthusiastically use our services and recommend us to friends and family. Please read the following policy to understand how your personal information will be treated as you make full use of our Site.</span></p>
                    <p><span><i class="far fa-hand-point-right"></i>  For further details/query regarding the privacy policy, you may contact us</span></p>
                </div>
            </div>
        </div>
    </div>
</section>